fix for issue #232
Corrects 

Error executing SQL:
com.amazon.redshift.util.RedshiftException: ERROR: column "control_person_id" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.

for redshift in query
```
     INSERT INTO n3c_ncats.N3C_CONTROL_MAP
     SELECT
 		person_id, 1 as buddy_num, NULL
 		FROM n3c_ncats.n3c_case_cohort
 		WHERE person_id NOT IN (
 			SELECT case_person_id
 			FROM n3c_ncats.N3C_CONTROL_MAP
 			WHERE buddy_num = 1
 			)
 
 		UNION
 
 		SELECT person_id, 2 as buddy_num, NULL
 		FROM n3c_ncats.n3c_case_cohort
 		WHERE person_id NOT IN (
 			SELECT case_person_id
 			FROM n3c_ncats.N3C_CONTROL_MAP
 			WHERE buddy_num = 2
 			)
```